In [1]:
import numpy as np

## 1 - Contar o número de transições de Falso para Verdadeiro em uma sequência.

In [2]:
x = np.array([False, True, False, False, True])

## 2 - Selecionar apenas números ímpares e eleva-os ao quadrado.

In [3]:
x = np.array([1, 2, 3, 4])

In [4]:
x[x%2!=0] ** 2

array([1, 9], dtype=int32)

## 3 - Somar todos os elementos divisíveis por 5.

In [5]:
x = np.array([1, 5, 12, 15, 20, 22])

In [6]:
sum(x[x%5==0])

40

## 4 Somar cada n valores em um vetor.

In [7]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
n = 4

In [8]:
x_len = len(x)/4

In [9]:
temp_n = 0
for i in range(int(x_len)):
    print(sum(x[temp_n:temp_n+i]))
    temp_n+=4

0
5
19


## 5 - Trocar todos os valores negativos em um vetor por zeros.

In [10]:
x = np.array([-3, -2, -1, 0, 1, 2, 3])

In [11]:
x[x<0] = 0
x

array([0, 0, 0, 0, 1, 2, 3])

##  6 - Contar número de valores pares em um vetor

In [12]:
x = np.array([1, 2, 3, 4, 5, 6, 7])

In [13]:
len(x[x%2==0])

3

## 7 - Encontrar máximos (picos) locais.

In [14]:
x = np.array([1, 2, 3, 4, 5, 4, 3, 2, 1, 2, 3, 2, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1])

In [15]:
x[1:-1][np.diff(np.diff(x)) < 0]

array([5, 3, 6])

##  8 - Verificar se número (não negativo) é primo.

In [16]:
def primo_teste(num):
    if num> 1:  
        for n in range(2,num):  
            if (num % n) == 0:  
                return False
        return True
    else:
        return False

In [17]:
primo_teste(31)

True